server:
  port: 0

spring:
  application:
    name: collection-service
  datasource:
    url: jdbc:mysql://localhost:3306/collection?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: wongyun
    password: tkfkdgo156
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    #    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}